### ISSUE TITLE
Notes on this Fork

### ISSUE THREAD

**Issue by hasezoey** [hasezoey/typegoose#1]
What this Fork currently has, and the original not:
- Github pages, where later typedoc will get deployed 
- Wiki, which currently points to readme & typedoc, in the future it will point to the pages
-  Milestones, to know which Issues will be worked on in which version

**Comment by hasezoey** [comment]
(I will close this, because its not an actual issue)

**Comment by hasezoey** [comment]
@Ben305 i wanted to ask, if it would be a better idea to use this (fork) as main typegoose, because the original got abandoned by its owner plus the npm package and travis?

to "transfer" to this repo, i would do these things:
- Try to resolve all PR's on the original Repo
- Try to resolve all Issues on the original Repo
- make a "Repo moved" notice (in README and in Issues)
- or if you have the rights (if you accept the collaborator status on this repo), you could transfer the open issues to here
- i would make a new npm package (named like `@hasezoey/typegoose`)

**Comment by Ben305** [comment]
I‘m on holiday at the moment, will get back to you in a week

**Comment by hasezoey** [comment]
@Ben305 ok, have fun :)

**Comment by hasezoey** [comment]
when https://github.com/hasezoey/typegoose/issues/1#issuecomment-517767760 is resolved, i will create an PR to which repo this will end

**Comment by hasezoey** [comment]
@Ben305 would you have the time to [decide /& make this](https://github.com/hasezoey/typegoose/issues/1#issuecomment-517767760)?

**Comment by B-Stefan** [comment]
@hasezoey  Thanks for adding new features and push this project forward! 
Might you have a release date or date range in mind? 

I'm just asking because we plan to use Typegoose in an enterprise solution and we need several fixes that are included in version 6.0.0.

**Comment by hasezoey** [comment]
> Might you have a release date or date range in mind?

2 thing need to be done:
1. https://github.com/szokodiakos/typegoose/pull/355 should get resolved - blocked by mongoose, the next version from them is targeted at 1. of September
2. like stated in commets above, this one needs to be done - to not get async with the master branch / main project....

**Comment by B-Stefan** [comment]
Nice! Thanks for the quick answer! 
Until the 1. of September, we could provide some additional fixes for the 6.0.0 version.

**Comment by hasezoey** [comment]
@Ben305 would you have the time to think about this (hasezoey#1)?

**Comment by Ben305** [comment]
Unfortunately I‘m unable to transfer the issues

**Comment by hasezoey** [comment]
can only the owner do that? (didnt read that anywhere, assumed a collaborator could do this too)

**Comment by hasezoey** [comment]
@Ben305 
then, we will let the issues and PR's there, and try to resolve them (/ at pr's close them and say to reopen them here) and an "Repo | Package Moved to hasezoey/typegoose"?

btw: what do you think about the github-pages documentation?

**Comment by k0hamed** [comment]
@hasezoey first of all, thanks for continuing the library. 

> i would then release v6.0.0 under the latest tag (in @hasezoey/typegoose) 

Won't the ownership of the npm package be transferred to you, so v6.0.0 gets released there? as I can see for now it's still owned by szokodiakos.

**Comment by hasezoey** [comment]
@k0hamed no, because szokodiakos owns the repo & npm package, i made new ones, this repo here & `@hasezoey/typegoose`

**Comment by k0hamed** [comment]
I guess [https://docs.npmjs.com/misc/disputes.html#tldr](this article) is addressing this case 

> - Get the author email with npm owner ls <pkgname>
> - Email the author, CC support@npmjs.com
> - After a few weeks, if there’s no resolution, we’ll sort it out.

As it's kind of confusing that ```typegoose``` is there while being migrated to ```@hasezoey/typegoose``` 

Otherwise, I'd suggest renaming this fork to a newer name, and releasing the npm package under the new name. 

I can open a discussion issue for that if you're interested.

**Comment by hasezoey** [comment]
@k0hamed i think it is perfectly fine how it is, and i dont give it a new name, because it is the same package, just newer

**Comment by k0hamed** [comment]
I'm sorry I'd have to disagree with you, 

> i dont give it a new name, because it is the same package, just newer

You can say that about any fork actually unless it becomes independent (it's not that rare, [oysttyer](https://github.com/oysttyer/oysttyer) is an example).  

The downside for the current state : 
- searching typegoose in npm will show this package as "just a fork" as the other 20 fork under "typegoose". (and google lists it in that box under "typegoose" with the other forks) 
A newcomer will get confused. 
- Forks are not searchable in github results unless you allow it in an advanced search (only if its stars are more than the original).
- As the only way to get here is from the original repo/package. it doesn't give the impression that this one is maintained independently or that typegoose as a whole is reliable for the future.
- It doesn't make sense to need a dead repo/package.
- "npm install @hasezoey/typegoose" instead of "npm install typegoose" doesn't feel right.

**Comment by hasezoey** [comment]
> "npm install @hasezoey/typegoose" instead of "npm install typegoose" doesn't feel right.

what about packages like `@angular`?

> Forks are not searchable in github results unless you allow it in an advanced search (only if its stars are more than the original).

i will contact github to remove the fork status

**Comment by k0hamed** [comment]
> what about packages like @angular?

```@angular/cli``` : the cli of the angular, not angular's fork of cli, ```@username/cli``` is way different. the case would be similar if it was ```@google/angular``` that you install while ```angular``` is a dead package, and google forked it.

**Comment by flx-l** [comment]
Thanks for maintaining typegoose. In my opinion, it would be really nice if you could try to get the ownership of the npm package `typegoose` as described [earlier](https://docs.npmjs.com/misc/disputes.html). But if it's not possible for some reason, `@hasezoey/typegoose` is ok too.

**Comment by hasezoey** [comment]
@k0hamed 
> searching typegoose in npm will show this package as "just a fork" as the other 20 fork under "typegoose". (and google lists it in that box under "typegoose" with the other forks)
A newcomer will get confused.
Forks are not searchable in github results unless you allow it in an advanced search (only if its stars are more than the original).

it is now an original Repo, not a fork anymore

**Comment by justinmchase** [comment]
Will this repo be deploying to the same npm package? Or will/is there a new npm package to get the updates from?

**Comment by hasezoey** [comment]
@justinmchase as stated in comments above & on the README, this package is now publish under `@hasezoey/typegoose`

**Comment by justinmchase** [comment]
Ok, I see it.

I recommend putting [this](https://github.com/hasezoey/typegoose#install) section at the tippy top of the readme. It will definitely be confusing for people and you will probably hear this question 10 million more times if that isn't easy to find.

**Comment by hasezoey** [comment]
@justinmchase [it is on top of the file?](https://github.com/hasezoey/typegoose#basic-usage)

**Comment by hisuwh** [comment]
If the original package is no longer being maintained then you really ought to claim ownership of the npm package and publish this there.

I realise this has been said before but I think it would be ideal.

**Comment by justinmchase** [comment]
@hisuwh Does npm support that? How can you claim ownership?

**Comment by hasezoey** [comment]
@justinmchase [simply google it](https://docs.npmjs.com/misc/disputes.html)

**Comment by justinmchase** [comment]
Nice, thanks. I didn't know they had that process, it seems pretty simple.
