### ISSUE TITLE
Must I change all of `typegoose` import statements to `import {} from from "@hasezoey/typegoose"`?

### ISSUE THREAD

**Issue by wxs77577** [hasezoey/typegoose#14]
Is there any way to keep the old codes, just add something like package alias to do this?

I tried to use `"typegoose":"@hasezoey/typegoose@next"`in `package.json`, but it does not work.

**Comment by hasezoey** [comment]
Closing this, because its not an Typegoose issue,

i dont know anything to alias it, sorry

**Comment by hasezoey** [comment]
one thing you could do, when on linux or mac: make a symlink to `typegoose` from `@hasezoey/typegoose` (didnt test this)

**Comment by atao60** [comment]
> I tried to use "typegoose":"@hasezoey/typegoose@next"in package.json, but it does not work.

Aliases are dealt through:
- tsconfig
`
        "paths": { "typegoose": ["../node_modules/@hasezoey/typegoose"] }
`
- babel config
`        ["module-resolver", { "alias": {   "typegoose": ["../node_modules/@hasezoey/typegoose"] } } ]
`
- ...
