### ISSUE TITLE
[Question] - Use Jest instead of Mocha? 

### ISSUE THREAD

**Issue by B-Stefan** [hasezoey/typegoose#20]
I would suggest using jest instead of mocha. 
For several reasons: 

1. Reduce dependency for chai 
2. More advanced mocking features 
3. Support to execute one test only direct inside the Webstorm GUI. 

What do you think about this suggestion?

**Comment by hasezoey** [comment]
Sorry, no, as we discovered in other issues, [please read here](https://hasezoey.github.io/typegoose/guides/known-issues/) and i'm just more familiar with mocha and chai

**Comment by B-Stefan** [comment]
No worries! 
Thanks for the hint with the typing error! 👍
