### ISSUE TITLE
Decorator Execution Order

### ISSUE THREAD

**Issue by hasezoey** [hasezoey/typegoose#23]
## Code Example

https://github.com/fabioformosa/typegoose-validation-error/tree/typegoosev6

## Do you know *why* it happenes?

Decorator Execution order
1. method & property decorators
2. class decorators

this conflicts because of:
1. @prop (property decorator) needs `name` of schema, which is applied in @modelOptions (class decorator)

**Comment by hasezoey** [comment]
Possible Solution:
- cache all decorator evaulations
- cache only inner-class ones

Cache Solutions:
- cache using Map<T, S>
- i dont know any other

@B-Stefan what do you think?

**Comment by fabioformosa** [comment]
Exactly, I fell in this trap just trying to add a `@TypeAlias` as class decorator.
Look at this:
https://stackoverflow.com/questions/57707455/typescript-decorator-get-class-decorator-value-from-method-decorator

I disagree with the answer, I think it's better to use a buffer to cache all metadata produced by method decorator, until class decorator is called.

**Comment by hasezoey** [comment]
i think its better to be called in buildSchema / _buildSchema, because a class decorator is optional

**Comment by hasezoey** [comment]
encountered a problem: caching is good and all, but how to make differing classes with the same name when schemaOptions nor options can be accessed in @prop? i couldnt find anything that makes a class / function unique ... so for now i made an (undocumented) variable `__uniqueID`

after doing the change to cached version, 3 tests fail, and i cannot figure out why (because it didnt fail before the cache change, and this only wraps all into another function)

WIP branch: https://github.com/hasezoey/typegoose/tree/r6/cache-inner-class-decorators

**Comment by hasezoey** [comment]
i looked into it again, didnt got it work, though about another possible solution:
"strip" the logic (that calls `schemas` and co) and do move them into `_buildSchema`

**Comment by hasezoey** [comment]
Update: added c8a5a18fc35b9c5461c0d78585ff566d57d550a7, which fixes the "build on subdocuments" error, but new ones show up, i think about for now (version 6) disabling the customName functions

**Comment by B-Stefan** [comment]
@hasezoey  Thanks for working on this! 
You are absolutely right - I ran into this issue yesterday again at another combination of nested entities.

**Comment by fabioformosa** [comment]
I'm going to pull your branch to try to solve the failing test. My proj constraint is to have more classes with the same name, this feature is strictly necessary to me. It would be a pity to give up, you're doing a very impressive work, I think this fork will became the new "official" repo.

**Comment by hasezoey** [comment]
Update: could theoretically fix "all" the errors, except:
- "_id: false" is just not working on @prop, only on @arrayProp

**Comment by fabioformosa** [comment]
Ok, great! Let me know when you push the new version `6.0.0-27`, so I try it in my project.
It's ok at the moment not use `_id: false`

**Comment by hasezoey** [comment]
> It's ok at the moment not use _id: false

its a requirement in biguser's test currently, and clutters the database

Note:
currently a cache (that caches the build schemas (`buildSchemas` in data.ts), but even after re-applying with `schema.set("_id", false)` it didnt even change)

**Comment by hasezoey** [comment]
> I think this fork will became the new "official" repo.

szokodiakos#387 got merged, it is now officially the new official

**Comment by hasezoey** [comment]
Update: i made it now commented out, and all tests pass, will squash all the WIP commits, and @fabioformosa could you evaluate/test it? (will make a pr, and update this comment)

**Comment by B-Stefan** [comment]
@hasezoey  This is working with my branch except for one test 
`expect(foundUser.job.jobType).to.not.have.property('_id');` is failing

**Comment by hasezoey** [comment]
@B-Stefan even the new 58490e8ecb1e6ce5324c947ac87976fa0bb57c9c?

**Comment by B-Stefan** [comment]
Did not tested this commit, yet.

**Comment by B-Stefan** [comment]
With 58490e8 all tests are green! 👍 nice work!

**Comment by hasezoey** [comment]
> nice work!

i would say its "not nice work" more like "hacky work" / "deactivating an existing feature" (`@prop({ _id: false })` dosnt work anymore / only in arrayprop sometimes??)

**Comment by fabioformosa** [comment]
I pushed a commit in this sample project `https://github.com/fabioformosa/typegoose-validation-error` (you know it) `branch typegoosev6`.
Add to `package.json` the package of typegoose from branch `r6/cache-inner-class-decorators`.
One test fails :(

**Comment by hasezoey** [comment]
easy issue: mongoose treats the one model (BarModel) as a reference (in fooService)

looking into a fix

**Comment by hasezoey** [comment]
easy fix: i made i mistake, it should have been `__uniqueID`, but when i set it it was `_uniqueID` (notice the double underscore)

fixed in 9f77b498e9e915bbe81239e6ae8726eb5dd47f0c

**Comment by fabioformosa** [comment]
It's work fine now, very nice work guy!
I owe one beer, let's add a donation button into the typegoose doc page.
Thank you!
PS: A final suggestion... IMHO, Typegoose would raise an exception if someone uses two classes with the same name, without disambiguate them by `collectionName` or `customName`.

**Comment by hasezoey** [comment]
@fabioformosa for now, the customName thing is disabled until this is fixed...

**Comment by B-Stefan** [comment]
> PS: A final suggestion... IMHO, Typegoose would raise an exception if someone uses two classes with the same name, without disambiguate them by collectionName or customName.

Actually I ran into this a couple of days ago. 
I had two classes with the same name and had to debug the reason why some properties where missing. An Error would be great!

**Comment by fabioformosa** [comment]
> @fabioformosa for now, the customName thing is disabled until this is fixed...

Ah ok. Which is the unsolved issue?

**Comment by hasezoey** [comment]
#23 (this)

**Comment by hasezoey** [comment]
@fabioformosa @B-Stefan is this soft error enough? 33e5014ca1f0198dc349b08b9401dd164076da6d

**Comment by fabioformosa** [comment]
All tests pass! I tried also here [https://github.com/fabioformosa/typegoose-validation-error](https://github.com/fabioformosa/typegoose-validation-error) and it's ok!
The only known issue is that about `_id: false` in `@prop`, isn't?

**Comment by hasezoey** [comment]
yes, that is why it currently dosnt get merged, because `_id: false` is an existing feature, which worked, and now somehow dosnt

**Comment by hasezoey** [comment]
PR got squash Merged in ada5cfb81798137aebb02dc68159d93809f3f828
