### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by mehmetnyarar** [hasezoey/typegoose#27]
I receive the following warning:

> DeprecationWarning: This Package got moved, please use `@hasezoey/typegoose` | github:hasezoey/typegoose

I removed `typegoose` and add it again but the warning is still there. What to do?

**Comment by hasezoey** [comment]
are you sure you removed `typegoose`? (`npm rm -s typegoose`)
and installed `@hasezoey/typegoose`? (`npm i -s @hasezoey/typegoose`)

if it dosnt work, try `rm -rf node_modules/` and `npm i -D`

**Comment by mehmetnyarar** [comment]
maybe i'm blind but i haven't seen anywhere regarding the installation command, so i was installing `typegoose` again but not `@hasezoey/typegoose` :)

yep, that works. i also had to change my imports to `import {} from '@hasezoey/typegoose'`. no problem so far, thanks.

**Comment by patarapolw** [comment]
Now it has to change to '@typegoose/typegoose' to get `instanceMethod` and `staticMethod` (without decorator) to work.

Please update the deprecation warning.

**Comment by hasezoey** [comment]
@patarapolw what is wrong with the deprecation warning?

**Comment by patarapolw** [comment]
@hasezoey It still says `@hasezoey/typegoose` when tried to install `npm i typegoose`; and the version is `5.9.x`, not `6.x.x`.

**Comment by hasezoey** [comment]
> @hasezoey It still says @hasezoey/typegoose when tried to install npm i typegoose; and the version is 5.9.x, not 6.x.x.

you mean on the original npm package? yes sorry i cant change this, this is the reason why the new package & repo were made (i dont have write permission to it) 
-> and i didnt do any pr, so that no version 5.9.2 would appear, because that would interfer with the 5.9.2 version on the new repo
