### ISSUE TITLE
[Discussion] Removal of options from getModelForClass making existingConnection usage challenging

### ISSUE THREAD

**Issue by duro** [hasezoey/typegoose#30]
I am attempting to migrate to 6.0. We are using NestJS as our framework, and more specifically, [kpfromer/nestjs-typegoose](https://github.com/kpfromer/nestjs-typegoose) for integrating Typegoose with NestJS.

In an effort to migrate nestjs-typegoose to 6.0, the first hangup I am running into is the removal of `options` from `getModelForClass`. Since the mongoose connection is setup ahead of time, and does not use the default connection, passing this connection into each model is challenging.

Giving this some additional thought, since the connection is added as part of a decorator, I'm having a hard time seeing how this could be done for even non-NestJS apps. Usually, an additional connection needs to be setup async ahead of time, which makes it hard to pass a connection to an imported file at module load time, without forcing the creation of a wrapper for each model that allows passing in a connection post module load time.

Any thoughts on how to get the existingConnection back into the model load time in a way more similar to how it was passed in via getModelForClass?

**Comment by duro** [comment]
For reference, this is the line in nestjs-typegoose that I'm having a hard time porting:

https://github.com/kpfromer/nestjs-typegoose/blob/master/src/typegoose.providers.ts#L29

Since NestJS is DI driven, it needs the ability to load the models into the DI layer, and provide them with the connection as well.

This makes me feel like adding a "connectionOptions" argument back to the `getModelForClass` function is justifiable.

Perhaps there is a way to keep both approach in place, and if connectionOptions are passed into `getModelForClass` it takes precedence  (or vice-vera, modelOptions take precedence).

**Comment by hasezoey** [comment]
thanks for letting us know before v6.0.0 releases, i would have a question:
would schemaOptions be needed in `getModelForClass` or just `existingConnection` & `existingMongoose`?

**Comment by B-Stefan** [comment]
We ran into the same issue: 
@duro  Hotfix for us: Use `Reflect.defineMetadata` to define the decorator data. 

I think only `existingConnection` & `existingMongoose` is necessary but schemaOptions would be nice to modify.

**Comment by hasezoey** [comment]
Fixed by #35
