### ISSUE TITLE
[Question] How to use the inject statics and methods

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [hasezoey/typegoose#37]
Following the docs: https://hasezoey.github.io/typegoose/docs/functions/addModelToTypegoose/

Jetbrains throws errors:
![Screenshot from 2019-09-15 20-40-07](https://user-images.githubusercontent.com/16192806/64926120-01974f00-d7fa-11e9-85d7-534acbdfafed.png)

I am trying to use the build schema to then inject the methods and statics.

```
  "dependencies": {
    "@hasezoey/typegoose": "^6.0.0-28",
```

**Comment by hasezoey** [comment]
not an issue with typegoose, `mongoose.model` expect you to give a name first, and then the schema
