### ISSUE TITLE
[Question]  use a new package name like 'typegoose-next'?

### ISSUE THREAD

**Issue by wxs77577** [hasezoey/typegoose#39]
It's quite difficult to remember your npm package name, since `typegoose` is not active, so why not use another package name?

**Comment by hasezoey** [comment]
I had this discussion already, so im closing this now, feel free to discuss here futrther

https://github.com/hasezoey/typegoose/issues/1#issuecomment-531272454

https://hasezoey.github.io/typegoose/guides/faq/#why-hasezoeytypegoose
