### ISSUE TITLE
Add default Classes

### ISSUE THREAD

**Issue by hasezoey** [hasezoey/typegoose#9]
- [ ] ~~add class for GridFS szokodiakos#216 hasezoey#10~~
- [x] add class for options `@modelOptions({ schemaOptions: { timestamps: true } })` (6.0.0-14)

(~~striked~~ means canceled)

**Comment by hasezoey** [comment]
Closed - because all listed tasks/features are implemented in 6.0.0

**Comment by remi2j** [comment]
Where can we find documentation for default classes ? I'm using 6.0

**Comment by hasezoey** [comment]
all documentation, guides and generated docs at https://typegoose.github.io/typegoose/

what you asked specifically https://typegoose.github.io/typegoose/guides/defaultClasses/

**Comment by remi2j** [comment]
Thanks. Note that the search results on _typegoose_.github.io are links to _hasezoey_.github.io, so they 404.
